### ISSUE TITLE
Shift + plus or minus sometimes controls captions when the video is in fullscreen

### ISSUE THREAD

**Issue by LoganDark** [avi12/youtube-like-dislike-shortcut#11]
Sometimes, when the video is in fullscreen, shift+plus (or shift+minus) will control the caption font size instead of liking or disliking the video.

Scrolling down or exiting fullscreen or doing anything to make the like/dislike buttons _visible on screen_ causes the shortcuts to start working again.

My theory is the shortcut is somehow failing to find the like buttons to click them so it doesn't cancel the default youtube behavior.

**Comment by avi12** [comment]
No worries, I pushed an update yesterday to address this issue
