### ISSUE TITLE
[Bug]  Not working anymore with the new youtube UI

### ISSUE THREAD

**Issue by aymenkouah** [avi12/youtube-like-dislike-shortcut#17]
### Describe the bug

The extension doesn't work anymore with the new UI

### How to reproduce

Open a YouTube video and press the assigned button to like/dislike

### Expected behavior

Pressing the assigned button should like/dislike the video

### What browser(s) can you reproduce the issue on?

Chrome, Firefox, Chromium Edge, Opera

### What OS does it occur on?

Windows

### What's the version you're running?

1.5.1

**Comment by avi12** [comment]
What does the new UI look like?

**Comment by aymenkouah** [comment]
![a](https://user-images.githubusercontent.com/58881830/190891128-1ec66b40-1618-4195-b537-1a73453b7367.jpg)
![Screenshot 2022-09-18 083618](https://user-images.githubusercontent.com/58881830/190891145-68c282fb-cc4c-4829-8268-539277f2544d.jpg)

**Comment by avi12** [comment]
Let me know if it works
[youtube-like-dislike-shortcut-1.5.2.zip](https://github.com/avi12/youtube-like-dislike-shortcut/files/9593322/youtube-like-dislike-shortcut-1.5.2.zip)

**Comment by aymenkouah** [comment]
it works now

**Comment by avi12** [comment]
Pushed [1.5.2](https://github.com/avi12/youtube-like-dislike-shortcut/releases/tag/1.5.2) to the extension stores
Please delete the sideloaded version and then force retrieving the update next week
