### ISSUE TITLE
[Bug] Likes can be removed on Linux

### ISSUE THREAD

**Issue by tynansdtm** [avi12/youtube-like-dislike-shortcut#18]
### Describe the bug

On Xubuntu, pressing the key a second time will remove the like from the video. Automatic like will also un-like the video if it was previously liked. Likes are not removed on Windows 10.

Issue found on Vivaldi browser, but replicated on a clean install of Chrome with no other extensions.

### How to reproduce

Open a video, press key twice and like will be added and then removed.

### Expected behavior

Pressing the like/dislike shortcut will only rate the video once, i.e., pressing again won't un-rate it

### What browser(s) can you reproduce the issue on?

Chrome, Vivaldi

### What OS does it occur on?

Linux

### What's the version you're running?

1.5.4

### Additional context

Xubuntu 22.04

**Comment by avi12** [comment]
Let me know if it works
[youtube-like-dislike-shortcut-1.5.5.zip](https://github.com/avi12/youtube-like-dislike-shortcut/files/9632548/youtube-like-dislike-shortcut-1.5.5.zip)

**Comment by tynansdtm** [comment]
No change, unfortunately. Pressing Shift-= just switches between liking and un-liking the video.

**Comment by avi12** [comment]
How about now?
[youtube-like-dislike-shortcut-1.5.5.zip](https://github.com/avi12/youtube-like-dislike-shortcut/files/9634838/youtube-like-dislike-shortcut-1.5.5.zip)

**Comment by tynansdtm** [comment]
This version has resolved my issue

**Comment by avi12** [comment]
Glad to hear it! Right now I'm investigating how to migrate to Plasmo
I've I complete the migration, I will combine this hotfix and push the corresponding update
