### ISSUE TITLE
Return YouTube Dislike extension not showing dislike count when used with Youtube like dislike shortcut

### ISSUE THREAD

**Issue by NaveenPNair** [avi12/youtube-like-dislike-shortcut#21]
### Describe the bug

I've been using the "Youtube like dislike shortcut" extension to quickly like and dislike videos on YouTube, but I've noticed that when I also have the "Return YouTube Dislike" extension enabled, it's not showing the dislike count. When I disable this extension, the dislike count is visible again. This is causing some confusion and inconvenience for me, as I prefer to use both extensions.

### How to reproduce

While these both extensions are enabled, the dislike count is not showing.

### Expected behavior

The "Return YouTube Dislike" extension should still show the dislike count even when used in conjunction with the "Youtube like dislike shortcut" extension.

### What browser(s) can you reproduce the issue on?

Chrome

### What OS does it occur on?

Windows

### What's the version you're running?

1.5.7

**Comment by avi12** [comment]
Are you talking about this?
![image](https://user-images.githubusercontent.com/6422804/236893690-d835e1fd-904f-48be-83e0-25875587e10c.png)

**Comment by NaveenPNair** [comment]
Yes

**Comment by NaveenPNair** [comment]
Thanks for your quick response. Looking forward to the fix!

**Comment by avi12** [comment]
I can't guarantee I'll push a fix today but I'll try to work on a fix by the end of the week

**Comment by NaveenPNair** [comment]
Ok, it's fine.

**Comment by avi12** [comment]
@NaveenPNair Let me know if this version works: [youtube-like-dislike-shortcut-1.6.0.zip](https://github.com/avi12/youtube-like-dislike-shortcut/files/11638121/youtube-like-dislike-shortcut-1.6.0.zip)

**Comment by avi12** [comment]
@NaveenPNair After a lot of blood, sweat, and tears, I finally pushed the update
