### ISSUE TITLE
Auto-like subscribed channels [Feature request] 

### ISSUE THREAD

**Issue by MelvinMod** [avi12/youtube-like-dislike-shortcut#23]
### Is your feature request related to a problem? Please describe

I need to like on what I subscribed

### Is it a change to the extension's functionality or to the pop-up settings page?

Extension's functionality

### If the latter, please propose a new design on Figma or describe it as detailed as possible

Auto like on subscribed channels

### Additional context

It's so awkward when you set 15 or 99 percent, and it's liking all channel's video

**Comment by avi12** [comment]
That's an interesting proposal

**Comment by avi12** [comment]
@MelvinMod Let me know if this version works: [youtube-like-dislike-shortcut-1.7.0.zip](https://github.com/avi12/youtube-like-dislike-shortcut/files/12703217/youtube-like-dislike-shortcut-1.7.0.zip)
