### ISSUE TITLE
[Bug] Percentage saving issue

### ISSUE THREAD

**Issue by riccardosimo** [avi12/youtube-like-dislike-shortcut#25]
### Describe the bug

Auto like feature doesn't work. And when i change the percentage from 70% (the default value) to any other percentage, it doesn't save the changes and when i reopen the settings it always shows 70%.

### How to reproduce

.

### Expected behavior

video should be liked after a certain percentage.

### What browser(s) can you reproduce the issue on?

Chrome

### What OS does it occur on?

Windows

### What's the version you're running?

119.0.6045.9

**Comment by SogaSuga** [comment]
I just started to have the same issue. 
Auto like after certain time stopped working, and the percentage won't save if I type in a new value. 
I remember there was a percentage counting text in front of the thumb up icon, but it's not there now.

Other functions are working like before, and I can change and save other setting options.
My browser is Firefox 119.0.1 on Windows 10.

**Comment by avi12** [comment]
I'll look into it

**Comment by mamapapaxp** [comment]
Just to add my confirmation of now experiencing the same problem. Had previously set it to auto-like at 95%, which worked (almost) flawlessly. Not sure if the addon has updated or if Chrome's recent updates have broken it. (Addon is at v1.7.0 and Chrome is at 119.0.6045.160) but having stopped functioning as expected, I modified the percentage to 75% and, after the video passes that point, I double-check and the percentage noted in the settings have reverted to my previously set 95%.
Other than that, my overdue praises for an awesome (and deceptively simple) addon.
