### ISSUE TITLE
[Bug] it's not working anymore, last 1-2 days

### ISSUE THREAD

**Issue by equivalentx** [avi12/youtube-like-dislike-shortcut#27]
### Describe the bug

no % counter, doesn't like videos, can't change like after watched % in settings

### How to reproduce

1

### Expected behavior

1

### What browser(s) can you reproduce the issue on?

Chrome

### What OS does it occur on?

Windows

### What's the extension version you're running?

1.7.0

### Make sure the bug wasn't reported before

- [X] I'm the first one to [report](https://github.com/avi12/youtube-auto-hd/issues?q=is%3Aissue) it

**Comment by avi12** [comment]
A few hours ago I pushed version [2.0.0](https://github.com/avi12/youtube-like-dislike-shortcut/releases/tag/2.0.0). It's up to the Chrome Web Store review team to approve it

**Comment by equivalentx** [comment]
...

**Comment by avi12** [comment]
My guess is that it will be approved tomorrow

**Comment by avi12** [comment]
Dang it, the reviewers take their time
![image](https://github.com/avi12/youtube-like-dislike-shortcut/assets/6422804/d11d156a-2163-4680-8a9a-65e455170edd)

**Comment by avi12** [comment]
It took a while but it finally got approved
![image](https://github.com/avi12/youtube-like-dislike-shortcut/assets/6422804/0822ff99-4227-43b7-a0fe-e2ff3ee8758c)

**Comment by equivalentx** [comment]
ty
