### ISSUE TITLE
[Bug]  Autolike count on ads progress

### ISSUE THREAD

**Issue by LuanPSB** [avi12/youtube-like-dislike-shortcut#29]
### Describe the bug

The autolike function counts towards the progress of your ads. So if I watch the selected percentage of the ad the video receives a like, videos with non-skippable 5s ads will always receive a like

### How to reproduce

You need to find a way to identify what is an ad and what is a video

### Expected behavior

Only mark as like when the percentage of the video is watched

### What browser(s) can you reproduce the issue on?

Chromium Edge

### What OS does it occur on?

Windows

### What's the extension version you're running?

2.0.0

### Make sure the bug wasn't reported before

- [X] I'm the first one to [report](https://github.com/avi12/youtube-auto-hd/issues?q=is%3Aissue) it

**Comment by avi12** [comment]
That's so weird, it shouldn't be a bug
https://github.com/avi12/youtube-like-dislike-shortcut/blob/23a9cc45a0ce35d1972a562f55dc85533d4c0312/src/contents/csui-ytr-auto-like-percent.svelte#L92-L96

**Comment by LuanPSB** [comment]
Maybe the restricted tracking options could be affecting this part?

**Comment by avi12** [comment]
No, the extension doesn't require this permission
It requires minimum permissions
