### ISSUE TITLE
doesn't work!

### ISSUE THREAD

**Issue by ChicChat** [avi12/youtube-like-dislike-shortcut#31]
### Describe the bug

I installed it, but it isn't functioning.
on the Google Chrome

### How to reproduce

i don't know

### Expected behavior

please fix it, tks.

### What browser(s) can you reproduce the issue on?

Chrome

### What OS does it occur on?

Windows

### What's the extension version you're running?

2.1.5

### Make sure the bug wasn't reported before

- [X] I'm the first one to [report](https://github.com/avi12/youtube-auto-hd/issues?q=is%3Aissue) it

**Comment by avi12** [comment]
How does your popup configuration look like?

**Comment by ChicChat** [comment]
it's ok now
tks for the reply ^^
I simply restart then it works

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
乾淨無病毒。www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

avi12 ***@***.***> 於 2024年3月2日 週六 下午6:14寫道：
