### ISSUE TITLE
yt shorts desktop

### ISSUE THREAD

**Issue by MrBaggieBug** [avi12/youtube-like-dislike-shortcut#9]
i recently saw how youtube shorts work on desktops now

https://www.youtube.com/shorts/fobJCljIENo

for example that one
i forked and honestly thought it would be a quick 20 minute adventure, i was wrong, it no work

plz send help

**Comment by avi12** [comment]
Thanks for letting me know about Shorts on the web!
On Friday I will hopefully have some time, and I will do my best to support rating Shorts as well
